name: Prettier
on: push
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Run Prettier
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write .
          same_commit: True
